import {Inter} from 'next/font/google'
import style from './app.module.css'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Posts',
    description: 'Generated by create next app',
    icons:{
        icon: '/img/icon.png'
    }
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={style.top}>
            <span>Next&Redux</span>
            <div className={style.postsList}>文章列表</div>
        </div>
        {children}
        </body>
        </html>
    )
}
