import style from './app.module.css'
import AddPostForm from "@/app/AddPostForm";
import PostsList from "@/app/PostsList";
import Image from "next/image";
import React from "react";

export let metadata = {
    title: 'Posts',
    description: 'Generated by create next app',
    icons:{
        icon: '/img/girl.jpg'
    }
}
export default function Home() {
    return (
        <div className={style.main}>
            <AddPostForm/>
            <PostsList/>
        </div>
    )
}
